Repository ministryofjustice/moj-frontend, pull requests merged in 2024-12, with the labels that each got.

#930 fix: (multi-select) allow multiple multi-selects on same page
  docs/examples/multi-select/index.njk
  src/moj/all.js
  src/moj/components/multi-select/README.md
  src/moj/components/multi-select/multi-select.js
Labels: bug

#956 Changing pagination results number
  docs/examples/pagination/index.njk
  src/moj/components/pagination/template.njk
Labels: bug

#925 Add interruption card
  docs/_includes/layouts/base.njk
  docs/_includes/layouts/component.njk
  docs/_includes/layouts/home.njk
  docs/assets/images/interruption-card-example-are-you-sure.png
  docs/assets/images/interruption-card-example-important-content.png
  docs/assets/images/interruption-card-example-non-contextual-error.png
  docs/assets/images/interruption-card-example-possible-error.png
  docs/assets/images/interruption-card-example-varied-outcome.png
  docs/components/interruption-card.md
  docs/examples/interruption-card/index.njk
  docs/examples/multi-select/index.njk
  docs/examples/pagination/index.njk
  src/moj/all.js
  src/moj/components/_all.scss
  src/moj/components/interruption-card/_interruption-card.scss
  src/moj/components/interruption-card/macro.njk
  src/moj/components/interruption-card/template.njk
  src/moj/components/multi-select/README.md
  src/moj/components/multi-select/multi-select.js
  src/moj/components/pagination/template.njk
Labels: staging:active

#997 fix(header): remove incorrectly applied filters in header component
  src/moj/components/header/template.njk
Labels: bug

#1023 build(preview): add branch preview cleanup workflow
  .github/workflows/branch-preview-cleanup.yml
Labels: preview:active

#967 docs(style guide): enable style guide for review
  .eleventy.js
  docs/assets/stylesheets/application.scss
  docs/assets/stylesheets/components/_accordions.scss
  docs/content-standards/index.md
  docs/content-standards/style-guide-updates.md
  docs/content-standards/style-guide.md
Labels: staging:active

#1031 docs: update what's new section
  docs/_includes/layouts/home.njk
Labels: staging:active

#989 feat(tabbed-view-documents): tabbed view documentation
  .eleventy.js
  docs/_includes/layouts/tabbed-component.njk
  docs/assets/stylesheets/application.scss
  docs/assets/stylesheets/components/_documentation_tabs.scss
  docs/components/date-picker.md
Labels: preview:active

#1033 docs: update apply service pattern page
  docs/_includes/layouts/service-patterns.njk
  docs/service-patterns/apply.md
  docs/service-patterns/index.md
Labels: preview:active
